name: release

on:
  schedule:
    - cron: '0 * * * *'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sh get_time.sh
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: *
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
