name: release

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: sh get_time.sh
#     - name: Tag
#       run: |
#         git tag "v${{ env.GitVersion_SemVer }}"
#         git push origin "v${{ env.GitVersion_SemVer }}"
#     - name: Release
#       uses: softprops/action-gh-release@v1
#       with:
#         files: /*
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
#     - name: Release
#       uses: ncipollo/release-action@v1.5.0
#       with:
#         artifacts: "*.sh"
#         token: ${{ secrets.GIT_RElEASE_TOKEN }}

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
#         automatic_release_tag: "latest"
        title: "Build"
        prerelease: false
        files: |
          *.sh
        
